# Generated by Django 3.2.6 on 2021-09-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210831_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Produkteliai'},
        ),
    ]
