# Generated by Django 3.2.6 on 2021-09-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.CharField(default='null', editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
