# Generated by Django 3.2.6 on 2021-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('delivery_cost', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
    ]
