# Generated by Django 3.2.6 on 2021-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_ordersummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
